# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "ngGirls Tel-Aviv 2016"
email: "info@ng-girls.com"
description: "ngGirls is a free one-day Angular 2 workshop for women"
baseurl: "/zeppelin"
url: "http://ngGirls.org"
permalink: "/blog/:title"
googleAnalyticsTrackingId: ""
googleAnalyticsSiteUrl: ""
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "ngGirls"
organizerAlternateName: "Angular Girls"
organizerDescription: "Free angular 2 workshops for women."
organizerEmail: "info@ng-girls.com"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://www.ng-girls.org/"

# Head
metaKeywords: "event, angular, google, programming, web, chrome, developers, javascript, single page application, tel aviv"
twitterAccount: "@AngularGirls"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "https://bit.ly/dfua-c4p"
c4sponsorsUrl: &c4sponsorsUrl "/assets/ngGirls_sponsors_flyer.pdf"


# Navigation
navigationLinks:
 - {permalink: "/#home", text: "Home"}
 - {permalink: "/#about", text: "About"}
 - {permalink: "/#description", text: "Be a part"}
 - {permalink: "/#organizing-team", text: "Team"}
 - {permalink: "/#location-map", text: "Location"}
 - {permalink: "/#partners", text: "Partners"}
 - {permalink: "/faq/", text: "FAQ"}
bottomNavigationLinks:
 - {link: "https://bit.ly/dfua-c4p", text: "Apply Now"}
rightNavigationButtons:
 - {link: "https://bit.ly/dfua-c4p", text: "Apply Now"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "ngGirls"
eventDate: "November 13, 2016, Tel-Aviv"
heroButtons:
 - {permalink: "/#tickets", text: "apply for the workhsop"}
 - {link: "https://bit.ly/dfua-c4p", text: "call for mentors"}
 - {permalink: *c4sponsorsUrl, newTab: true, text: "call for sponsors"}

# About Block
aboutTitle: "About ngGirls"
aboutBlock:
 - {title: "motivation", image: "conference.jpg", text: "ngGirls is aims to introduce women to the world of technology and increase the diversity. Angular 2 is a great technology to start with. We believe this is a win-win situation!" }
 - {title: "operation", image: "workshop.jpg", text: "One-day workshop to build and deploy Angular 2 app with the help of dedticated mentors. Later that week join the community at AngularUP international conference!" }
 - {title: "participation", image: "hackathon.jpg", text: "If you're a committed, motivated woman who wants to step into the Web Development world - your place is with us! Apply now!<br>Want to help? Please get in touch!" }

# Description Block (Latest News in index)
descriptionTitle: "Be a Part of ngGirls"
descriptionBlock:
 - {title: "Who is it for?", template: "description-who-is-it-for.html", link: "/#faq", linkTitle: "Check out the FAQ"}
 - {title: "Can I help?", template: "description-can-i-help.html", link: "/#help", linkTitle: "contact us", text: "Of course! There are several ways you can help: <br/>
                  <ul><li><b>Sponsors</b> - with your help we can make this event truely awesome!
                  From supplying tickets to AngularUP, through supplying lunch, to swag - lots of opportunities to help. "}

# Latest News Block
latestNewsTitle: "Latest news"

# Organizing Team Block
organizingTeamImage: "rockstar-speakers.jpg"
organizingTeamCount: 2
organizingTeamTitle: "Organizing Team"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 2
rockstarSpeakersTitle: "Organizing Team"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "Campus Tel Aviv"
eventLocationLink: "https://www.campus.co/tel-aviv/"
eventStreetAddress: "Electra Tower- 34th Floor<br>98 Yigal Alon Street"
eventAddressLocality: "Tel Aviv"
eventAddressLocalityRegion: ""
eventPostalCode: "79000"
eventAddressCountry: "Israel"
eventStartTime: "2014-10-25T10:00"
eventDoorTime: "09:00"
eventEndTime: "2014-10-25T20:00"
eventPlaceCoordinates: "32.0699972,34.7940928"
mapCenterCoordinates: "32.0692972,34.7910428"
mapMobileCenterCoordinates: "32.0683802,34.7947528"
mapUrl: "https://www.google.com/maps/place/Google/@32.0700544,34.7919324,17z/data=!3m1!4b1!4m5!3m4!1s0x151d4b9f106b7d51:0x5d3968071ecd1735!8m2!3d32.0700544!4d34.7941211"
viewOnMap: "View on Google Maps"

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Kinopalace Cinema"
venueFeatures: ["3 huge cinema screens", "Doulby Digital Surround EX audio system", "Located directly in the city center"]

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners"
partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

# Footer
socialLinks:
 - {link: "https://plus.google.com/b/102444623953913144164", icon: "google-plus"}
 - {link: "https://twitter.com/intent/user?screen_name=GDGLviv", icon: "twitter"}
 - {link: "https://facebook.com/GDGLviv", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://gdg.org.ua", text: "GDG.org.ua"}
   - {link: "https://developers.google.com", text: "Google Developers"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:info@ng-girls.com", text: "info@ng-girls.com"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Code of Conduct"}

# FAQ
faqTitle: "Frequently Asked Questions"

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: true
discusShortName: "devfestua"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: "ngGirls is aims to introduce women to the world of technology and increase the diversity. The organization is inspired by Django Girls."
